import { NextPage } from 'next'
import Head from 'next/head'
import FilterList from '../../components/FilterList/FilterList'
import ItemViewCard from '../../components/ItemsCard/ItemViewCard'

const filterData = [
    {
        name: 'Lighter',
        url: '/products/123',
    },
    {
        name: 'Matches',
        url: '/products/124',
    },
]

const ItemsListView: NextPage = () => {
    return (
        <div className="min-h-screen min-w-full py-2 text-primaryText">
            <Head>
                <title>Shop</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex w-full flex-col justify-between p-2 lg:flex-row">
                <div className="p-2 lg:w-1/6 lg:space-y-20 lg:p-0">
                    <FilterList
                        title="All categories"
                        options={filterData}
                    />
                    <FilterList
                        title="Filters"
                        options={filterData}
                    />
                </div>
                <div className="space-y-20 p-2 lg:hidden">
                    <FilterList
                        title="Sort by"
                        options={filterData}
                    />
                </div>
                <div className="grid w-full grid-cols-1 place-items-center gap-8 px-2 lg:grid-cols-3">
                    {products.map((item) => (
                        <ItemViewCard
                            key={item.id}
                            name={item.name}
                            id={item.id}
                            image={item.image}
                            url={item.url}
                            description={item.description}
                            price={item.price}
                        />
                    ))}
                </div>
                <div className="hidden w-1/6 space-y-20 lg:block">
                    <FilterList
                        title="Sort by"
                        options={filterData}
                    />
                </div>
            </main>
        </div>
    )
}

export default ItemsListView

export const products = [
    {
        id: 1,
        name: 'Kurs makeup',
        price: 80.0,
        image: '/images/kurs_makeup.jpg',
        description:
            'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quos quas rerum a porro ratione repellendus iste, vero corrupti, quibusdam magni consequuntur nostrum quam consectetur cupiditate atque ducimus unde, numquam tempora.',
        url: '/api/products/1',
    },
    {
        id: 2,
        name: 'Krzemień wieczny',
        price: 80.0,
        image: '/images/test.png',
        description:
            'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quos quas rerum a porro ratione repellendus iste, vero corrupti, quibusdam magni consequuntur nostrum quam consectetur cupiditate atque ducimus unde, numquam tempora.',
        url: '/api/products/1',
    },
    {
        id: 3,
        name: 'Krzemień wieczny',
        price: 80.0,
        image: '/images/test.png',
        description:
            'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quos quas rerum a porro ratione repellendus iste, vero corrupti, quibusdam magni consequuntur nostrum quam consectetur cupiditate atque ducimus unde, numquam tempora.',
        url: '/api/products/1',
    },
    {
        id: 4,
        name: 'Krzemień wieczny',
        price: 80.0,
        image: '/images/test.png',
        description:
            'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quos quas rerum a porro ratione repellendus iste, vero corrupti, quibusdam magni consequuntur nostrum quam consectetur cupiditate atque ducimus unde, numquam tempora.',
        url: '/api/products/1',
    },
    {
        id: 5,
        name: 'Krzemień wieczny',
        price: 80.0,
        image: '/images/test.png',
        description:
            'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quos quas rerum a porro ratione repellendus iste, vero corrupti, quibusdam magni consequuntur nostrum quam consectetur cupiditate atque ducimus unde, numquam tempora.',
        url: '/api/products/1',
    },
    {
        id: 6,
        name: 'Krzemień wieczny',
        price: 80.0,
        image: '/images/test.png',
        description:
            'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quos quas rerum a porro ratione repellendus iste, vero corrupti, quibusdam magni consequuntur nostrum quam consectetur cupiditate atque ducimus unde, numquam tempora.',
        url: '/api/products/1',
    },
    {
        id: 7,
        name: 'Krzemień wieczny',
        price: 80.0,
        image: '/images/test.png',
        description:
            'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quos quas rerum a porro ratione repellendus iste, vero corrupti, quibusdam magni consequuntur nostrum quam consectetur cupiditate atque ducimus unde, numquam tempora.',
        url: '/api/products/1',
    },
    {
        id: 8,
        name: 'Krzemień wieczny',
        price: 80.0,
        image: '/images/test.png',
        description:
            'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quos quas rerum a porro ratione repellendus iste, vero corrupti, quibusdam magni consequuntur nostrum quam consectetur cupiditate atque ducimus unde, numquam tempora.',
        url: '/api/products/1',
    },
    {
        id: 9,
        name: 'Krzemień wieczny',
        price: 80.0,
        image: '/images/test.png',
        description:
            'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quos quas rerum a porro ratione repellendus iste, vero corrupti, quibusdam magni consequuntur nostrum quam consectetur cupiditate atque ducimus unde, numquam tempora.',
        url: '/api/products/1',
    },
    {
        id: 10,
        name: 'Krzemień wieczny',
        price: 80.0,
        image: '/images/test.png',
        description:
            'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quos quas rerum a porro ratione repellendus iste, vero corrupti, quibusdam magni consequuntur nostrum quam consectetur cupiditate atque ducimus unde, numquam tempora.',
        url: '/api/products/1',
    },
]
