import { NextPage } from 'next'
import Head from 'next/head'
import FilterList from '../../components/FilterList/FilterList'
import ItemViewCard from '../../components/ItemsCard/ItemViewCard'

const filterData = [
    {
        name: 'Lighter',
        url: '/products/123',
    },
    {
        name: 'Matches',
        url: '/products/124',
    },
]

const ItemsListView: NextPage = () => {
    return (
        <div className="min-h-screen min-w-full py-2 text-primaryText">
            <Head>
                <title>Shop</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex w-full flex-col justify-between p-2 lg:flex-row">
                <div className="p-2 lg:w-1/6 lg:space-y-20 lg:p-0">
                    <FilterList
                        title="All categories"
                        options={filterData}
                    />
                    <FilterList
                        title="Filters"
                        options={filterData}
                    />
                </div>
                <div className="space-y-20 p-2 lg:hidden">
                    <FilterList
                        title="Sort by"
                        options={filterData}
                    />
                </div>
                <div className="grid w-full grid-cols-1 place-items-center gap-8 px-2 lg:grid-cols-3">
                    <ItemViewCard />
                    <ItemViewCard />
                    <ItemViewCard />
                    <ItemViewCard />
                    <ItemViewCard />
                    <ItemViewCard />
                    <ItemViewCard />
                    <ItemViewCard />
                    <ItemViewCard />
                    <ItemViewCard />
                    <ItemViewCard />
                    <ItemViewCard />
                    <ItemViewCard />
                    <ItemViewCard />
                    <ItemViewCard />
                    <ItemViewCard />
                </div>
                <div className="hidden w-1/6 space-y-20 lg:block">
                    <FilterList
                        title="Sort by"
                        options={filterData}
                    />
                </div>
            </main>
        </div>
    )
}

export default ItemsListView
