import type { NextPage } from 'next'
import Head from 'next/head'
import ItemsCard from '../components/ItemsCard/ItemsCard'
import ItemsMainSection from '../components/ItemsMainSection/ItemsMainSection'

const Home: NextPage = () => {
    return (
        <div className="text-primaryText min-h-screen min-w-full bg-black px-2 py-6">
            <Head>
                <title>Shop</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <ItemsMainSection
                mian={<ItemsCard />}
                top={<ItemsCard />}
                bottom={<ItemsCard />}
            />
        </div>
    )
}

export default Home
