import type { NextPage } from 'next'
import Head from 'next/head'
import BestSellersSection from '../components/BestSellersSection/BestSellersSection'
import CategoryItemCard from '../components/CategoryItemCard/CategoryItemCard'
import CategorySlider from '../components/CategorySlider/CategorySlider'
import ItemsCard from '../components/ItemsCard/ItemsCard'
import ItemsMainSection from '../components/ItemsMainSection/ItemsMainSection'
import ItemsSecoundSection from '../components/ItemsSecoundSection/ItemsSecoundSection'
import TextSection from '../components/TextSection/TextSection'

const Home: NextPage = () => {
    return (
        <div className="text-primaryText min-h-screen min-w-full py-2">
            <Head>
                <title>Shop</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <section className="px-2">
                    <ItemsMainSection
                        main={
                            <ItemsCard
                                name="Krzemień wieczny"
                                price={70}
                            />
                        }
                        top={
                            <ItemsCard
                                name="Krzemień wieczny"
                                price={70}
                            />
                        }
                        bottom={
                            <ItemsCard
                                name="Krzemień wieczny"
                                price={70}
                            />
                        }
                    />
                </section>
                <section>
                    <CategorySlider>
                        <CategoryItemCard />
                        <CategoryItemCard />
                        <CategoryItemCard />
                        <CategoryItemCard />
                        <CategoryItemCard />
                        <CategoryItemCard />
                        <CategoryItemCard />
                        <CategoryItemCard />
                    </CategorySlider>
                </section>
                <section>
                    <TextSection />
                </section>
                <section className="px-2">
                    <ItemsSecoundSection
                        main={
                            <ItemsCard
                                name="Krzemień wieczny"
                                price={70}
                            />
                        }
                        top={
                            <ItemsCard
                                name="Krzemień wieczny"
                                price={70}
                            />
                        }
                        bottom={
                            <ItemsCard
                                name="Krzemień wieczny"
                                price={70}
                            />
                        }
                    />
                </section>
                <section>
                    <BestSellersSection>
                        <CategoryItemCard />
                        <CategoryItemCard />
                        <CategoryItemCard />
                        <CategoryItemCard />
                        <CategoryItemCard />
                        <CategoryItemCard />
                    </BestSellersSection>
                </section>
            </main>
        </div>
    )
}

export default Home
